### ISSUE TITLE
Improve security and useability by not directly using code from wikipage but using git

### ISSUE THREAD

**Issue by WolfgangFahl** [Kenny2github/Piwo#10]
Instead of directly taking the code from the Gram name space an improved mechanism would be to backup the code with a git repository. Any manipulation of the code would need to be checked in to git and the mechanism for the credential handling would allow extra security as needed by the organisation running the wiki up to not allowing any modification at all directly from the wiki. The code executed would be the code from the git repository and there might be a warning if the code displayed is not the same. The display could be directly in the wiki or just a pointer to the git repository. This mechanism would also allow to add tests and continuous integration. Another side effect is that the git repository could be a public one and by adding the tag "PIWO" people could share their PIWO based solutions easily.

**Comment by Kenny2github** [comment]
This can just be done with a bot instead - make a git repo, and have a bot make edits to the Gram namespace upon push to master branch.

**Comment by WolfgangFahl** [comment]
Thx for the reply - this is a good idea but security wise not the same level of protection.
