### ISSUE TITLE
Syntax highlighting does not work

### ISSUE THREAD

**Issue by WolfgangFahl** [Kenny2github/Piwo#9]
How is 
$wgSyntaxHighlightModels

to be used to get syntax highlighting work?.

I tried
```php
global $wgSyntaxHighlightModels;
$wgSyntaxHighlightModels['Piwo'] = 'python';
```
since
Piwo.class.php has the following code:
```
global $wgSyntaxHighlightModels;
if (isset($wgSyntaxHighlightModels)) {
   $wgSyntaxHighlightModels[CONTENT_MODEL_PIWO] = 'python3';
```
I also looked into the result of:
http://phpcrossref.com/xref/mediawiki/_variables/wgSyntaxHighlightModels.html

but couldn't understand what is going on and there is no syntaxhighlighting effect.
![grafik](https://user-images.githubusercontent.com/1336221/97268285-ec2d8a80-182b-11eb-9c2a-56c5066977db.png)

Personally I'd prefer if the Gram pages would be normal wiki pages and the source code would be put into
```
<syntaxhighlight lang='python'>
<syntaxhighlight>
```
tags may be using sections for naming the code . 
That way meta-information for the source code could be given - there could be proper naming of the modules in lower case and there could be multiple source code files on a single page.

**Comment by Kenny2github** [comment]
I have a working solution for making SyntaxHighlight work - now I'm trying to figure out how to cache it so that pygments isn't run every time the page loads.

**Comment by WolfgangFahl** [comment]
Greate -i'll stay tuned.
